### ISSUE TITLE
Resource Sharing for Subnets

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-resource-access-manager-user-guide#1]
https://docs.aws.amazon.com/ram/latest/userguide/getting-started-sharing.html

Might make sense to add a disclaimer that only non-default subnets can be shared with other accounts within your organization (and may not work without organizations in place).

Information about VPC Sharing below:
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html

**Comment by meiringa** [comment]
Hello, 

Thank you for pointing this out. While I don't believe that this is the best place in the doc to discuss any resource-specific restrictions or requirements, I do agree that we should highlight the fact that special restrictions might apply. As an alternative solution, I'm going to add a note here to suggest that you refer to the relevant service's User Guide for the resource-specific info.

Thanks again. And if you have any other questions, please don't hesitate to let me know.

Thanks
Ashley
