### ISSUE TITLE
Update the conditions in the Security>IAM sections of the documentation

### ISSUE THREAD

**Issue by bksarthak** [awsdocs/aws-resource-access-manager-user-guide#5]
In the following URL https://docs.aws.amazon.com/ram/latest/userguide/iam-policies.html

The IAM conditions are repeated twice under the `ram:RequestedResourceType` section. I've created a pull request with fixed formatting and removing the duplication.

**Comment by julieso** [comment]
My apologies for the delayed response. I've merged your pull request.
